# Generated by Django 5.2.8 on 2025-11-22 03:58

import academy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
                ("duration_in_week", models.DateTimeField()),
                ("course_image", models.ImageField(upload_to="course_image/")),
            ],
        ),
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("enrolled_course", models.CharField()),
                (
                    "trainer",
                    models.CharField(
                        verbose_name=academy.models.TrainerModel.trainer_name
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("expertise", models.CharField()),
                ("trainer_photo", models.ImageField(upload_to="trainer_photo/")),
            ],
        ),
    ]
