# Generated by Django 5.2.8 on 2025-11-22 04:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainermodel",
            name="trainer_id",
            field=models.UUIDField(default=2, verbose_name=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentmodel",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academy.trainermodel",
            ),
        ),
    ]
