# Generated by Django 5.2.8 on 2025-11-22 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_trainermodel_trainer_id_alter_studentmodel_trainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmodel",
            name="enrolled_course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academy.coursemodel",
            ),
        ),
    ]
